
no_index: 
  directory: 
    - inc
    - t
generated_by: Module::Install version 0.54
distribution_type: module
version: 0.52
name: YAML
author: "Ingy d\xC3\xB6t Net <ingy@cpan.org>"
license: perl
requires: 
  Test::More: 0.62
  Test::Base: 0.46
  perl: 5.6.1
  Spiffy: 0.27
abstract: YAML Ain't Markup Language (tm)
