
no_index: 
  directory: 
    - inc
    - t
generated_by: Module::Install version 0.54
distribution_type: module
version: 0.53
name: YAML
author: "Ingy d\xC3\xB6t Net <ingy@cpan.org>"
license: perl
requires: 
  Class::Spiffy: 0.12
  Test::Base: 0.47
  perl: 5.6.1
abstract: YAML Ain't Markup Language (tm)
