name: YAML
version: 0.36
abstract: YAML Ain't Markup Language
author: Brian Ingerson <ingy@cpan.org>
license: perl
distribution_type: module
requires:
  perl: 5.005003
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
